server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: reloj-service
          uri: lb://reloj-service
          predicates:
            - Path=/reloj/**
        - id: reporte-service
          uri: lb://reporte-service
          predicates:
            - Path=/reporte/**